name: Run Cypress Tests on PR to dev 

on:
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Start the application
        run: yarn start &
        env:
          CI: true

      - name: Wait for application to be ready
        run: |
          # Wait for the application to be ready
          for i in `seq 1 10`; do
            curl -sSf http://localhost:4200 && break
            sleep 5
          done

      - name: Run Cypress tests
        run: npx cypress run --config video=false,screenshotOnRunFailure=false
        env:
          CYPRESS_baseUrl: http://localhost:4200
