name: Run Cypress Tests on PR to dev

on:
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'

      - name: Navigate to dotnet directory
        run: cd server/server

      

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x'

      - name: Install .NET dependencies
        run: dotnet restore
        working-directory: ./server/server

      - name: Build .NET project
        run: dotnet build --no-restore
        working-directory: ./server/server

      - name: Start .NET server
        run: dotnet watch  &
        working-directory: ./server/server
        env:
          ASPNETCORE_ENVIRONMENT: Development

      - name: Wait for .NET server to be ready
        run: |
          # Wait for the .NET server to be ready
          for i in `seq 1 10`; do
            curl -sSf https://localhost:44344 && break
            sleep 5
          done

      - name: Navigate to angular directory
        run: cd angular

      - name: Install Angular dependencies
        run: yarn install
        working-directory: ./angular

      - name: Start Angular application
        run: yarn start &
        working-directory: ./angular
        env:
          CI: true

      - name: Wait for Angular application to be ready
        run: |
          # Wait for the Angular application to be ready
          for i in `seq 1 10`; do
            curl -sSf http://localhost:4200 && break
            sleep 5
          done
        working-directory: ./angular

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: ./angular
        env:
          CYPRESS_baseUrl: http://localhost:4200

